### PR TITLE
Creates UI tests

### LINKED ISSUE #10: Add tests
It would be nice to have some basic set of tests so we can be sure everything is OK when changes are made.

### PR DESCRIPTION
**Pull request by daveneff**
Closes #10

Hey @VojtaStavik,

This is my first time committing to open source so I'm pretty excited! I added UI tests based on the issue I saw in #10 .

To do this I had to create an XCode project and some screens to associate the UI tests with.

I also changed some minor things in VSTextField.swift which were causing the tests to fail. Hence the tests :) 

Let me know if you have any feedback or questions -- thanks!

### CODE REVIEW

**Comment by VojtaStavik** [comment]
Hey @daveneff, thank you very much for this PR! I'm currently very busy and I'll do my best to review this PR later this week. Code reviews and comments from others are also welcome 🎉

**Comment by VojtaStavik** [comment]
Hey @daveneff, sorry it took me so long. What an impressive work you did here! Wow 👍 . I really like it. Let me invite you to become a collaborator on this project. After you resolve the conflict, feel free to merge this PR.

**Review by VojtaStavik — APPROVED** [review]

**Comment by munirwanis** [comment]
@daveneff any updates on this?

**Comment by daveneff** [comment]
@munirwanis  Sorry for the delay -- just merged.

@VojtaStavik No problem! Thanks creating this in the first place :)

**Pull request merged**
